# Movie Project

## Objetives

- make a simple content-based recommender
- calculate similarities through cosen similarity
- evaluate the model

## Code

In [10]:
import kagglehub
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("chaitanyahivlekar/large-movie-dataset")
df = pd.read_csv(r"C:\Users\dagui\.cache\kagglehub\datasets\chaitanyahivlekar\large-movie-dataset\versions\1\movies_dataset.csv")

In [11]:
del df['Unnamed: 0'], df['User_Id']
df_small = df.sample(n=5000) # Select 40 random rows of your dataset
df_small.head()

Movie_Name  Rating  \
14303969                   Gladiator (2000)     5.0   
11657814               I'm Not There (2007)     3.0   
9338365   X-Men: Days of Future Past (2014)     4.5   
24809275                        Bolt (2008)     3.0   
19309424         Hanging Garden, The (1997)     4.0   

                                               Genre  
14303969                      Action|Adventure|Drama  
11657814                                       Drama  
9338365                      Action|Adventure|Sci-Fi  
24809275  Action|Adventure|Animation|Children|Comedy  
19309424                               Drama|Romance

In [13]:
df_small['Genre'].dropna()
df_small.head()

Movie_Name  Rating  \
14303969                   Gladiator (2000)     5.0   
11657814               I'm Not There (2007)     3.0   
9338365   X-Men: Days of Future Past (2014)     4.5   
24809275                        Bolt (2008)     3.0   
19309424         Hanging Garden, The (1997)     4.0   

                                               Genre  
14303969                      Action|Adventure|Drama  
11657814                                       Drama  
9338365                      Action|Adventure|Sci-Fi  
24809275  Action|Adventure|Animation|Children|Comedy  
19309424                               Drama|Romance

In [14]:
df_small.describe()

Rating
count  5000.000000
mean      3.541600
std       1.048375
min       0.500000
25%       3.000000
50%       3.500000
75%       4.000000
max       5.000000

In [15]:
# This separates the genres
df_small['Genre']  = df_small['Genre'].str.split('|')

from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
genres_encoded = mlb.fit_transform(df_small['Genre'])

genres_df = pd.DataFrame(genres_encoded, columns = mlb.classes_, index = df_small.index)
print(genres_df.head())


          (no genres listed)  Action  Adventure  Animation  Children  Comedy  \
14303969                   0       1          1          0         0       0   
11657814                   0       0          0          0         0       0   
9338365                    0       1          1          0         0       0   
24809275                   0       1          1          1         1       1   
19309424                   0       0          0          0         0       0   

          Crime  Documentary  Drama  Fantasy  Film-Noir  Horror  IMAX  \
14303969      0            0      1        0          0       0     0   
11657814      0            0      1        0          0       0     0   
9338365       0            0      0        0          0       0     0   
24809275      0            0      0        0          0       0     0   
19309424      0            0      1        0          0       0     0   

          Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western  
14303969  

In [17]:
df_final = pd.concat([df_small[['Movie_Name']], genres_df],axis=1)

In [18]:
df_final.head()

Movie_Name  (no genres listed)  Action  \
14303969                   Gladiator (2000)                   0       1   
11657814               I'm Not There (2007)                   0       0   
9338365   X-Men: Days of Future Past (2014)                   0       1   
24809275                        Bolt (2008)                   0       1   
19309424         Hanging Garden, The (1997)                   0       0   

          Adventure  Animation  Children  Comedy  Crime  Documentary  Drama  \
14303969          1          0         0       0      0            0      1   
11657814          0          0         0       0      0            0      1   
9338365           1          0         0       0      0            0      0   
24809275          1          1         1       1      0            0      0   
19309424          0          0         0       0      0            0      1   

          ...  Film-Noir  Horror  IMAX  Musical  Mystery  Romance  Sci-Fi  \
14303969  ...          0       0     0        0        0        0       0   
11657814  ...          0       0     0        0        0        0       0   
9338365   ...          0       0     0        0        0        0       1   
24809275  ...          0       0     0        0        0        0       0   
19309424  ...          0       0     0        0        0        1       0   

          Thriller  War  Western  
14303969         0    0        0  
11657814         0    0        0  
9338365          0    0        0  
24809275         0    0        0  
19309424         0    0        0  

[5 rows x 21 columns]

In [19]:
features_matrix = genres_df.values
print(features_matrix)

[[0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
import numpy as np


def cosine_sim(v1,v2):
    simil = np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
    return simil

print(f"similitud entre Gladiator y I'm not there: {cosine_sim(features_matrix[0],features_matrix[1])}")

similitud entre Gladiator y I'm not there: 0.5773502691896258
